create table ajee.ajee (
idPersonne bigint(100) primary key auto_increment, 
nom varchar(100), 
prenom varchar(100), 
sexe varchar(50), 
identifiant varchar(100), 
mdp varchar(100), 
email varchar(100), 
adresse varchar(100), 
cp varchar(10), 
ville varchar(100), 
telFixe varchar(50), 
telPort varchar(50),
fax varchar(50),
dateNaissance varchar(50), 
lieuNaissance varchar(100), 
numSecu varchar(50), 
nationalite varchar(100), 
situation varchar(100), 
fonction varchar(100),
positionEntreprise varchar(100), 
cadre boolean, 
coeff varchar(100), 
salaire varchar(100), 
visiteMedicale date, 
montantTransport varchar(100), 
voiture boolean,
nbCV int,
nbKm varchar(100),
mutuelle boolean, 
ticketResto boolean, 
dateCreation date,  
dateModification timestamp, 
bloque boolean, 
raisonBlocage varchar(500), 
listeDoc varchar (1000) 
);