/*USE jsmt;
DROP table listdocument;
DROP table personne;*/
create table personneWS(
LP_IDPERSONNE BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LP_NOM VARCHAR(255) NOT NULL DEFAULT 'nom',
LP_PRENOM VARCHAR(255) NOT NULL DEFAULT 'prenom',
LP_SEXE VARCHAR(255) NOT NULL DEFAULT 'masculin',
LP_IDENTIFIANT VARCHAR(255) NOT NULL DEFAULT '',
LP_MDP VARCHAR(255) NOT NULL DEFAULT '',
LP_EMAIL VARCHAR(255) NOT NULL DEFAULT '',
LP_ADRESSE VARCHAR (255) NOT NULL DEFAULT '',
LP_CP VARCHAR(255) NOT NULL DEFAULT '',
LP_VILLE VARCHAR(255) NOT NULL DEFAULT '',
LP_TELFIXE VARCHAR(255) NOT NULL DEFAULT '',
LP_TELPORT VARCHAR(255) NOT NULL DEFAULT '',
LP_FAX VARCHAR(255) DEFAULT '',
LP_DATENAISSANCE DATE DEFAULT '1970-01-01',
LP_LIEUNAISSANCE VARCHAR(255) NOT NULL DEFAULT '',
LP_NUMSECU VARCHAR(255) NOT NULL DEFAULT '123456789123456',
LP_NATIONALITE VARCHAR(255) NOT NULL DEFAULT '',
LP_SITUATION VARCHAR(255) NOT NULL DEFAULT '',
LP_FONCTION VARCHAR(255) NOT NULL DEFAULT '',
LP_POSITION VARCHAR(255) NOT NULL DEFAULT '100',
LP_CADRE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_COEFF VARCHAR(255) NOT NULL DEFAULT '100',
LP_SALAIRE VARCHAR(255) NOT NULL DEFAULT '10',
LP_VISITEMEDICALE DATE NOT NULL DEFAULT '1970-01-01',
LP_MONTANTTRANSPORT VARCHAR(255) NOT NULL DEFAULT '0',
LP_VOITURE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_NBCV INTEGER(6) NOT NULL DEFAULT 0,
LP_NBKM VARCHAR(255) NOT NULL DEFAULT '0',
LP_MUTUELLE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_TICKETRESTO VARCHAR(255) NOT NULL DEFAULT 'false',
LP_ADMIN VARCHAR(255) NOT NULL DEFAULT 'false',
LP_DATECREATION DATE NOT NULL DEFAULT '1970-01-01',
LP_DATEMODIFICATION TIMESTAMP NOT NULL,
LP_BLOQUE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_RAISONBLOCAGE TEXT NOT NULL
);

INSERT INTO jmst.personneWS(LP_NOM, LP_PRENOM, LP_SEXE, LP_IDENTIFIANT, LP_MDP, LP_EMAIL, LP_ADRESSE, LP_CP, LP_VILLE, LP_TELFIXE, LP_TELPORT, LP_FAX, LP_DATENAISSANCE, LP_LIEUNAISSANCE, LP_NUMSECU, LP_NATIONALITE, LP_SITUATION, LP_FONCTION, LP_POSITION, LP_CADRE, LP_COEFF, LP_SALAIRE, LP_VISITEMEDICALE, LP_MONTANTTRANSPORT, LP_VOITURE, LP_NBCV, LP_NBKM, LP_MUTUELLE, LP_TICKETRESTO, LP_ADMIN, LP_DATECREATION, LP_DATEMODIFICATION, LP_BLOQUE, LP_RAISONBLOCAGE)VALUES('Cresson','Thomas','masculin','thcr','password','test.test@test.fr','testadresse','10000','Ville test','123456789','123456789','','2010-03-06','lieu de naissance','194523689741235','fr','situation test','fonction','100','false','1','32000','2010-03-06','70','false','20','200','false','false','true','2010-03-06','2016-09-03 00:19:30.673','false','pas de raison');
INSERT INTO jmst.personneWS(LP_NOM, LP_PRENOM, LP_SEXE, LP_IDENTIFIANT, LP_MDP, LP_EMAIL, LP_ADRESSE, LP_CP, LP_VILLE, LP_TELFIXE, LP_TELPORT, LP_FAX, LP_DATENAISSANCE, LP_LIEUNAISSANCE, LP_NUMSECU, LP_NATIONALITE, LP_SITUATION, LP_FONCTION, LP_POSITION, LP_CADRE, LP_COEFF, LP_SALAIRE, LP_VISITEMEDICALE, LP_MONTANTTRANSPORT, LP_VOITURE, LP_NBCV, LP_NBKM, LP_MUTUELLE, LP_TICKETRESTO, LP_ADMIN, LP_DATECREATION, LP_DATEMODIFICATION, LP_BLOQUE, LP_RAISONBLOCAGE)VALUES('Cassagne','Johann','masculin','joca','password','test.test@test.fr','testadresse','10000','Ville test','123456789','123456789','','2010-03-06','lieu de naissance','194523689741235','fr','situation test','fonction','100','false','1','32000','2010-03-06','70','false','20','200','false','false','true','2010-03-06','2016-09-03 00:19:30.673','false','pas de raison');
INSERT INTO jmst.personneWS(LP_NOM, LP_PRENOM, LP_SEXE, LP_IDENTIFIANT, LP_MDP, LP_EMAIL, LP_ADRESSE, LP_CP, LP_VILLE, LP_TELFIXE, LP_TELPORT, LP_FAX, LP_DATENAISSANCE, LP_LIEUNAISSANCE, LP_NUMSECU, LP_NATIONALITE, LP_SITUATION, LP_FONCTION, LP_POSITION, LP_CADRE, LP_COEFF, LP_SALAIRE, LP_VISITEMEDICALE, LP_MONTANTTRANSPORT, LP_VOITURE, LP_NBCV, LP_NBKM, LP_MUTUELLE, LP_TICKETRESTO, LP_ADMIN, LP_DATECREATION, LP_DATEMODIFICATION, LP_BLOQUE, LP_RAISONBLOCAGE)VALUES('Kadri','Souad','feminin','soka','password','test.test@test.fr','testadresse','10000','Ville test','123456789','123456789','','2010-03-06','lieu de naissance','294523689741235','fr','situation test','fonction','100','false','1','32000','2010-03-06','70','false','20','200','false','false','true','2010-03-06','2016-09-03 00:19:30.673','false','pas de raison');
INSERT INTO jmst.personneWS(LP_NOM, LP_PRENOM, LP_SEXE, LP_IDENTIFIANT, LP_MDP, LP_EMAIL, LP_ADRESSE, LP_CP, LP_VILLE, LP_TELFIXE, LP_TELPORT, LP_FAX, LP_DATENAISSANCE, LP_LIEUNAISSANCE, LP_NUMSECU, LP_NATIONALITE, LP_SITUATION, LP_FONCTION, LP_POSITION, LP_CADRE, LP_COEFF, LP_SALAIRE, LP_VISITEMEDICALE, LP_MONTANTTRANSPORT, LP_VOITURE, LP_NBCV, LP_NBKM, LP_MUTUELLE, LP_TICKETRESTO, LP_ADMIN, LP_DATECREATION, LP_DATEMODIFICATION, LP_BLOQUE, LP_RAISONBLOCAGE)VALUES('Denis','Marc','masculin','made','password','test.test@test.fr','testadresse','10000','Ville test','123456789','123456789','','2010-03-06','lieu de naissance','194523689741235','fr','situation test','fonction','100','false','1','32000','2010-03-06','70','false','20','200','false','false','true','2010-03-06','2016-09-03 00:19:30.673','false','pas de raison');

/*DELETE FROM jmst.personne WHERE LP_IDPERSONNE>20;*/

/*alter table jmst.personne
add LP_POSITION varchar(255) not null default '1.0';*/

/*CREATE TABLE listdocument(
LD_IDPERSONNE BIGINT NOT NULL,
LD_IDDOCUMENT BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LD_NOMDOCUTIL VARCHAR(255) NOT NULL DEFAULT '',
LD_NOMDOCFILE VARCHAR(255) NOT NULL DEFAULT '',
LD_TIME	BIGINT(255) NOT NULL DEFAULT 0,
LD_COMMENTAIRE TEXT(32) NOT NULL, 
LD_DOCUMENT BLOB NOT NULL 
);*/




