/*create table listpersonne.personne(
ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LOGIN VARCHAR(255) NOT NULL,
PASS VARCHAR(255) NOT NULL,
NOM VARCHAR(255) NOT NULL,
PRENOM VARCHAR(255) NOT NULL,
MAIL VARCHAR(255) NOT NULL,
NATIONALITE VARCHAR(255) NOT NULL,
ADMIN VARCHAR(255) NOT NULL
);*/



