/*alter table marchand.marchand
add(NOM VARCHAR(30)); */
/*ALTER TABLE test.meuble
DROP nom_colonne;*/
/*drop table marchand.marchand;*/
DROP TABLE personneWS;
create table personneWS(
LP_IDPERSONNE BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
LP_NOM VARCHAR(255) NOT NULL DEFAULT 'nom',
LP_PRENOM VARCHAR(255) NOT NULL DEFAULT 'prenom',
LP_SEXE VARCHAR(255) NOT NULL DEFAULT 'masculin',
LP_IDENTIFIANT VARCHAR(255) NOT NULL DEFAULT '',
LP_MDP VARCHAR(255) NOT NULL DEFAULT '',
LP_EMAIL VARCHAR(255) NOT NULL DEFAULT '',
LP_ADRESSE VARCHAR (255) NOT NULL DEFAULT '',
LP_CP VARCHAR(255) NOT NULL DEFAULT '',
LP_VILLE VARCHAR(255) NOT NULL DEFAULT '',
LP_TELFIXE VARCHAR(255) NOT NULL DEFAULT '',
LP_TELPORT VARCHAR(255) NOT NULL DEFAULT '',
LP_FAX VARCHAR(255) DEFAULT '',
LP_DATENAISSANCE DATE DEFAULT '1970-01-01',
LP_LIEUNAISSANCE VARCHAR(255) NOT NULL DEFAULT '',
LP_NUMSECU VARCHAR(255) NOT NULL DEFAULT '123456789123456',
LP_NATIONALITE VARCHAR(255) NOT NULL DEFAULT '',
LP_SITUATION VARCHAR(255) NOT NULL DEFAULT '',
LP_FONCTION VARCHAR(255) NOT NULL DEFAULT '',
LP_POSITION VARCHAR(255) NOT NULL DEFAULT '100',
LP_CADRE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_COEFF VARCHAR(255) NOT NULL DEFAULT '100',
LP_SALAIRE VARCHAR(255) NOT NULL DEFAULT '10',
LP_VISITEMEDICALE DATE NOT NULL DEFAULT '1970-01-01',
LP_MONTANTTRANSPORT VARCHAR(255) NOT NULL DEFAULT '0',
LP_VOITURE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_NBCV INTEGER(6) NOT NULL DEFAULT 0,
LP_NBKM VARCHAR(255) NOT NULL DEFAULT '0',
LP_MUTUELLE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_TICKETRESTO VARCHAR(255) NOT NULL DEFAULT 'false',
LP_ADMIN VARCHAR(255) NOT NULL DEFAULT 'false',
LP_DATECREATION DATE NOT NULL DEFAULT '1970-01-01',
LP_DATEMODIFICATION TIMESTAMP NOT NULL,
LP_BLOQUE VARCHAR(255) NOT NULL DEFAULT 'false',
LP_RAISONBLOCAGE TEXT NOT NULL
);
