create database ajee;
USE ajee;

CREATE USER 'ajee'@'%' IDENTIFIED BY '***';

GRANT USAGE ON * . * TO 'ajee'@'%' IDENTIFIED BY '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON `ajee` . * TO 'tous'@'%';